name: xlifesmp
version: '${version}'

main: org.succeptivitydev.xlifesmp.ThirdLifePlugin
api-version: '26.2'
load: POSTWORLD
commands:
  life:
    description: Main command for the plugin
    usage: /life
  revive:
    description: Revive a player
    usage: /revive <player>
    permission: xlifesmp.revive
  setlives:
    description: Set the number of lives for a player
    usage: /setlives <player> <lives>
    permission: xlifesmp.setlives